### PR TITLE
feat: add cython monotonic_time_coarse implementation

### PR DESCRIPTION
**Pull request by bdraco**
This is ~44% faster vs the python implementation

### CODE REVIEW

**Comment by jaymunro** [comment]
I'm walking in the dark here. Trying to help out with the Bermuda tracker integration referenced above.

If the existing code imports as:
```
from homeassistant.util.dt import monotonic_time_coarse
```

What should this be changed to for the new location?

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/blob/4fa76801afc320e82de8a2c4d19de3d6b53d80f7/homeassistant/components/bluetooth/__init__.py#L123

**Comment by bdraco** [comment]
or `from bluetooth_data_tools import monotonic_time_coarse`

**Comment by bugtoo** [comment]
> or `from bluetooth_data_tools import monotonic_time_coarse`

This works nicely, thanks ❤️

**Comment by jaymunro** [comment]
Working here too. I'll add a PR to the integration

**Pull request merged**
